# Generated by Django 3.1.5 on 2021-01-15 12:13

import django_jsonfield_backport.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('faceModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facemodels',
            name='data',
            field=django_jsonfield_backport.models.JSONField(null=True),
        ),
    ]
