# Generated by Django 3.1.5 on 2021-01-17 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faceModel', '0003_auto_20210115_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facemodels',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
