# Generated by Django 3.1.5 on 2021-01-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('faceModel', '0004_auto_20210117_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facemodels',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
