# Generated by Django 3.1.5 on 2021-01-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('faceModel', '0005_auto_20210117_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facemodels',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
